workflows:
  main:
    - name: Configure Java
      script:
        - echo "org.gradle.java.home=C:/Program Files/Java/jdk-17.0.2" >> android/gradle.properties
        - flutter build appbundle --debug